version: "3"

services:
  ckan-dev:
    container_name: ckan-dev-project
    build:
      context: ckan/
      dockerfile: Dockerfile.dev
      args:
        - TZ=${TZ}
    env_file:
      - .env
    links:
      - db
      - solr
      - redis
      - datapusher
    ports:
      - "0.0.0.0:${CKAN_PORT}:5000"
    volumes:
      - ./src:/srv/app/src_extensions
      - ckan_storage-project:/var/lib/ckan
    

  datapusher:
    container_name: datapusher-project
    build:
      context: datapusher/
    ports:
      - "8800:8800"

  db:
    container_name: db-project
    env_file:
      - .env
    build:
      context: postgresql/
    environment:
      - PGDATA=/var/lib/postgresql/data/db
    volumes:
      - pg_data-project:/var/lib/postgresql/data

  solr:
    container_name: solr-project
    image: ckan/ckan-solr:2.9-solr8
    ports:
      - "8983:8983"
    volumes:
      - solr_data-project:/opt/solr/server/solr/ckan/data/index

  redis:
    container_name: redis-project
    image: redis:alpine

volumes:
  ckan_storage-project:
  pg_data-project:
  solr_data-project:
